---

- name: Install MySQL Server
  apt: pkg={{ item }} state=present
  notify: mysql-restart
  become: yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

# - name: Remove .my.cnf for root
#   file:
#     path: "/root/.my.cnf"
#     state: absent
#   become: yes

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user:
    name=root
    host={{ item }}
    password={{ dbms_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  become: yes

- name: copy .my.cnf file with root password credentials
  template: src=../../common/templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes

- name: remove the MySQL test database
  action: mysql_db db=test state=absent
  become: yes